---
title: "PFNA 1 compartment Run MCMC (v8)"
author: "Weihsueh Chiu, Claire Lay, Parker Malek"
date: "`r format(Sys.time(), '%F')`"
knit: (function(inputFile, encoding) {outdir = file.path(dirname(inputFile), 'markdown', paste0(format(Sys.time(), '%F'))); if(!dir.exists(outdir)){dir.create(outdir)}; rmarkdown::render(inputFile, encoding = encoding, output_format = 'all', output_dir = outdir) })
output:
  word_document: default
  html_notebook:
    code_folding: hide
    df_print: kable
    toc: yes
    toc_depth: 5
---

```{r setup}
library(coda)
library(bayesplot) 
library(ggplot2)
library(tidyverse)
library(reshape2)
library(here)
knitr::opts_chunk$set(echo = TRUE, dpi = 300 )
```

Set up MCSim file

```{r mcsim}
# this markdown file must be saved in top level directory for the following to work; the mcsim code depends on getwd results.
mdir <- "MCSim"
source(here::here(mdir,"setup_MCSim.R"))
# Make mod.exe (used to create mcsim executable from model file)
makemod() 
```

## Indiv and Pop data MCMC - 4 chains

Running model.
```{r MCMC  model file, include=FALSE}
set.seed(314159)
# Make model executable
model_file<- "PFAS_1cpt_v8.pop.MCMC.model.R"
makemcsim(model_file)

in_file <- "PFNA_1cpt_v8.PopMCMC_MeanIndivTrainTest.in.R" 

# in_file created partly with code in Generate_Individual_Simulations.rmd and partly manually (by copy-pasting the simulation code generated by the rmd into the R script)
```


```{r MCMC run, include=FALSE}
# Run model

out_file <- ""
chains <- list()
checks <- data.frame()
samps <- data.frame()
samps.mcmc <- list()

for (chainnum in 1:4) {
  outtest.list <- mcsim(model_file = model_file,
                        in_file = in_file,
                        chainnum = chainnum)
  print("Chain: "); print(chainnum)
  outcheck <- outtest.list$df_check
  outchain <- outtest.list$df_out
  # Only save second half (after burn-in)
  outsamp <- outchain[floor(nrow(outchain) / 2):nrow(outchain), -1]
  chains <- c(chains, list(as.matrix(outchain)))
  checks <- rbind(checks, outcheck)
  samps <- rbind(samps, outsamp)
  samps.mcmc <- c(samps.mcmc, list(mcmc(outsamp)))
}

samps.mcmclist <- as.mcmc.list(samps.mcmc)
save(samps.mcmclist, file = "PFNA_1cpt_v8_samps.mcmc_full.Rdata") 
# Contains monte carlo sampling for each param
 

```


```{r do-multicheck, include=FALSE}
multicheck <- mcsim.multicheck(model_file=model_file,
                                in_file=in_file, nsamp = 500)
save(multicheck, file="PFNA_1cpt_v8_multicheck.Rdata")
```

```{r echo=FALSE}
devtools::session_info()
```